# environment: "dev", "test", "stg", "prod"
environment: "prod"

cassandra:
  hosts: "192.168.33.10:39042"
  keyspace: "finance"

kafka:
  bootstrap.servers: "192.168.33.10:39092"
  topics: 
    processor: "processor"
    analyzer: "analyzer"

